import { DISASTERS, type DisasterId } from './effects';
import { SELF_DESTRUCT_DURATIONS } from './self-destruct';
import { REAL_MAP_SIZES } from '../server/map-limits.mjs';

const paths: Record<string, string> = {
  link: '<path d="m10 13 4-4M8 15l-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0M16 9l1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/>',
  timer: '<circle cx="12" cy="14" r="8"/><path d="M9 2h6M12 2v4M18 7l2-2M12 10v4l3 2"/>',
  meteor: '<path d="m21 3-8 8M21 9l-4 4M15 3l-4 4"/><path d="M13.6 10.4a6.5 6.5 0 1 1-6-1.8L14 3l-1 6 5-1-4.4 2.4Z"/><path d="m7 14 2 2"/>',
  bomb: '<circle cx="10" cy="14" r="7"/><path d="m15 9 2-2-2-2-2 2M17 5c1-3 4-2 4-4M20 6h2M18 2V0"/>',
  crosshair: '<circle cx="12" cy="12" r="7"/><path d="M12 2v5M12 17v5M2 12h5M17 12h5"/><circle cx="12" cy="12" r="1"/>',
  radiation: '<circle cx="12" cy="12" r="2"/><path d="M10 8 7 3a10 10 0 0 0-5 9h6m6-4 3-5a10 10 0 0 1 5 9h-6m-7 3-3 5a10 10 0 0 0 12 0l-3-5"/>',
  tornado: '<path d="M3 3h18M5 7h14M7 11h10M6 15h8M9 19h3M10 22h1"/>',
  waves: '<path d="M2 6c3-5 5 5 8 0s5 5 8 0 4 0 4 0M2 12c3-5 5 5 8 0s5 5 8 0 4 0 4 0M2 18c3-5 5 5 8 0s5 5 8 0 4 0 4 0"/>',
  activity: '<path d="M2 12h4l3-9 5 18 3-9h5"/>',
  zap: '<path d="m13 2-9 12h7l-1 8 10-13h-7l1-7Z"/>',
  droplets: '<path d="M12 2s-7 8-7 12a7 7 0 0 0 14 0c0-4-7-12-7-12Z"/><path d="M9 15a3 3 0 0 0 3 3"/>',
  mountain: '<path d="m2 21 7-16 4 4 3-6 6 18H2Z"/><path d="m6 12 4 2 3-5 4 3"/>',
  ufo: '<ellipse cx="12" cy="12" rx="10" ry="4"/><path d="M6 9a6 6 0 0 1 12 0M6 19l-1 3M12 20v3M18 19l1 3M7 12h.1M12 13h.1M17 12h.1"/>',
  orbit: '<circle cx="12" cy="12" r="3"/><ellipse cx="12" cy="12" rx="11" ry="5" transform="rotate(-35 12 12)"/><path d="M5 3c-4 5 8 21 14 17M4 4h.1M20 19h.1"/>',
  city: '<path d="M3 21V9h6V3h7v10h5v8H3ZM6 12h.1M6 16h.1M12 7h1M12 11h1M12 15h1M17 17h1M9 21V9"/>',
  map: '<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5ZM9 3v16M15 5v16"/>',
  play: '<path d="m8 4 13 8-13 8V4Z"/>', pause: '<path d="M8 4v16M16 4v16"/>',
  sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1 1M18 18l1 1M5 19l1-1M18 6l1-1"/>',
  moon: '<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>',
  volume: '<path d="m11 4-6 5H2v6h3l6 5V4ZM15 8a6 6 0 0 1 0 8M18 5a10 10 0 0 1 0 14"/>',
  mute: '<path d="m11 4-6 5H2v6h3l6 5V4ZM16 9l6 6M22 9l-6 6"/>',
  help: '<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 1 1 4 3c-1 0-1 1-1 2M12 17h.1"/>',
  settings: '<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',
  expand: '<path d="M8 3H3v5M16 3h5v5M21 16v5h-5M8 21H3v-5"/>',
  reset: '<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7"/>',
  camera: '<rect x="2" y="6" width="20" height="15" rx="3"/><circle cx="12" cy="13" r="4"/><path d="m6 6 2-3h8l2 3"/>',
  shuffle: '<path d="m3 4 18 16M17 20h4v-4M3 20l6-6M15 8l6-4M17 4h4v4"/>',
  chevron: '<path d="m9 5 7 7-7 7"/>', x: '<path d="m6 6 12 12M18 6 6 18"/>',
  pointer: '<path d="m4 3 6 18 3-8 8-3L4 3Z"/>', people: '<circle cx="9" cy="7" r="3"/><path d="M3 21v-4a6 6 0 0 1 12 0v4M16 4a3 3 0 0 1 0 6M18 14a5 5 0 0 1 3 4v3"/>',
  wind: '<path d="M2 8h13a3 3 0 1 0-3-3M2 12h18a3 3 0 1 1-3 3M2 16h6a3 3 0 1 1-3 3"/>',
};
export function icon(name: string, cls = '') { return `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.meteor}</svg>`; }
export const el = <T extends HTMLElement = HTMLElement>(id: string) => document.getElementById(id) as T;
export function buildUI() {
  el('app').innerHTML = `
  <canvas id="world" aria-label="Интерактивный 3D-город. Выберите катастрофу и нажмите на город."></canvas>
  <div id="vignette"></div><div id="flash"></div>
  <div id="loading"><div class="loading-mark">${icon('city')}</div><h1>CRUSH<span>CITY</span></h1><p>Строим кое-что прекрасное.<br>Пока что.</p><div class="loading-bar"><i></i></div><small>ГЕНЕРАЦИЯ ГОРОДА</small></div>
  <header class="topbar hud">
    <a class="brand" href="#" aria-label="Crush City">${icon('city')}<div>CRUSH<span>CITY</span><small>DISASTER SANDBOX</small></div><b>ALPHA</b></a>
    <div class="world-stats"><div><span class="stat-icon">${icon('people')}</span><div><small>НАСЕЛЕНИЕ</small><strong id="population">—</strong></div></div><i></i><div><span class="stat-icon">${icon('city')}</span><div><small>ЗДАНИЯ</small><strong id="buildings">—</strong></div></div><i></i><div class="damage-stat"><span class="damage-dot"></span><div><small>РАЗРУШЕНИЕ</small><strong id="damage">0<span>%</span></strong></div><div class="damage-track"><b id="damage-fill"></b></div></div></div>
    <div class="top-actions"><span id="fps-counter" title="Частота кадров"><b id="fps">—</b><small>FPS</small></span><button id="sound" class="icon-btn" title="Звук" aria-label="Включить звук">${icon('mute')}</button><button id="help" class="icon-btn" title="Управление" aria-label="Управление">${icon('help')}</button><button id="settings" class="icon-btn" title="Настройки" aria-label="Настройки">${icon('settings')}</button><button id="fullscreen" class="icon-btn" title="На весь экран" aria-label="На весь экран">${icon('expand')}</button></div>
  </header>
  <section class="location hud"><div class="eyebrow"><span class="live-dot"></span><span id="sim-status">СИМУЛЯЦИЯ АКТИВНА</span></div><h1 id="city-name">Нью-Хейвен</h1><p id="city-subtitle">Прибрежный мегаполис <span>•</span> Золотой час</p><button id="maps" class="text-button">${icon('map')} Сменить город ${icon('chevron')}</button><button id="share-city" class="text-button" hidden>${icon('link')} Поделиться местом</button></section>
  <div class="time-tools hud"><button id="daytime" class="glass icon-btn" aria-label="Сменить время суток" title="Сменить время суток">${icon('sun')}</button><button id="self-destruct" class="glass icon-btn" aria-label="Самоуничтожение города" aria-haspopup="dialog" aria-controls="self-destruct-dialog" aria-pressed="false" title="Самоуничтожение города">${icon('timer')}</button><button id="camera-home" class="glass icon-btn" aria-label="Вернуть камеру" title="Вернуть камеру · H">${icon('reset')}</button><button id="cinematic" class="glass icon-btn" aria-label="Кинорежим" title="Кинорежим · C">${icon('camera')}</button>
    <div id="self-destruct-status" class="glass" hidden><div class="self-destruct-heading"><span>САМОУНИЧТОЖЕНИЕ</span><button id="self-destruct-stop" class="icon-btn" aria-label="Остановить самоуничтожение" title="Остановить самоуничтожение">${icon('x')}</button></div><div class="self-destruct-timing"><strong id="self-destruct-countdown">0:30</strong><span id="self-destruct-phase">Случайные катастрофы</span></div><progress id="self-destruct-progress" max="1" value="0" aria-label="Время самоуничтожения"></progress></div>
  </div>
  <div id="toast" class="toast" role="status"><span id="toast-icon"></span><div><strong id="toast-title"></strong><small id="toast-description"></small></div></div>
  <aside class="overview hud"><div class="overview-title"><span>ОБЗОР ГОРОДА</span><button id="minimap-region" class="mini-switch" aria-label="Показать острова на мини-карте">Регион</button><span class="live-dot"></span></div><canvas id="minimap" width="220" height="160" aria-label="Мини-карта города. Нажмите, чтобы переместить камеру."></canvas><div class="map-meta"><span id="seed-label">SEED: NEW-HAVEN</span><b>N ↑</b></div><div class="overview-event"><span id="event-dot"></span><span id="event-status">В городе всё спокойно</span></div></aside>
  <div class="bottom-area hud"><div class="above-dock"><div class="hint" id="action-hint">${icon('pointer')}<span>Выберите катастрофу. <b>Нажмите на город.</b></span></div><span id="squad-status" class="squad-status" hidden></span><div class="playback glass"><button id="pause" title="Пауза · Пробел" aria-label="Пауза">${icon('pause')}</button><i></i><button data-speed="0.25">¼×</button><button data-speed="1" class="active">1×</button><button data-speed="2">2×</button><i></i><button id="rebuild" title="Восстановить город" aria-label="Восстановить город">${icon('reset')}</button></div></div>
  <section class="disaster-dock"><div class="dock-head"><div class="categories" role="tablist"><button class="active" data-category="all" role="tab">Все инструменты <b>15</b></button><button data-category="nature" role="tab">Стихия</button><button data-category="weapons" role="tab">Арсенал</button><button data-category="space" role="tab">Космос</button><button data-category="troops" role="tab">Десант</button></div><label class="power">МОЩНОСТЬ <input id="power" type="range" min="0.5" max="2" value="1" step="0.25" aria-label="Мощность катастрофы"><strong id="power-value">1.0×</strong></label></div><div id="squad-options" class="squad-options" hidden><span>КОМАНДА</span><button data-team="0" class="active" aria-pressed="true" style="--team:#60baf0">Синие</button><button data-team="1" aria-pressed="false" style="--team:#ed7064">Красные</button><button data-team="2" aria-pressed="false" style="--team:#e6c265">Золотые</button><small>Разные команды враждуют · союзники не стреляют друг в друга</small></div><div id="disasters" class="disaster-list">${DISASTERS.map((d, i) => `<button class="disaster-card ${i === 0 ? 'selected' : ''}" data-disaster="${d.id}" data-type="${d.category}" style="--accent:${d.color}" title="${d.name}: ${d.sub}" aria-pressed="${i === 0}"><span class="card-number">${i < 9 ? i + 1 : '✦'}</span><span class="disaster-icon">${icon(d.icon)}</span><strong>${d.name}</strong><small>${d.sub}</small></button>`).join('')}</div></section>
  <footer><span class="desktop-controls"><kbd>ЛКМ</kbd> клик — применить / тянуть — двигаться <i>·</i> <kbd>ПКМ</kbd> вращать <i>·</i> <kbd>W A S D</kbd> двигаться <i>·</i> <kbd>КОЛЕСО</kbd> масштаб</span><span class="touch-controls">Касание — инструмент · 1 палец — двигать · 2 — вращать / зум</span><span class="engine-status"><span class="live-dot"></span> WEBGL 2 <i>·</i> БЕЗГРАНИЧНАЯ ПЕСОЧНИЦА</span></footer></div>
  <button id="exit-cinematic">${icon('x')} Вернуть интерфейс <kbd>C</kbd></button>
  <div id="map-credit" hidden>Карта: © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors · ODbL</div>
  <dialog id="real-map-dialog" aria-labelledby="real-map-title"><div class="dialog-head"><div><span class="eyebrow">РЕАЛЬНАЯ КАРТА · ВАША ПЕСОЧНИЦА</span><h2 id="real-map-title">Любое место. Новая история.</h2></div><button class="icon-btn close-dialog" aria-label="Закрыть">${icon('x')}</button></div><form id="real-search-form" class="real-search-row"><input id="real-search" aria-label="Название города или места" placeholder="Город, район или достопримечательность" minlength="3" maxlength="100"><button id="real-search-button" type="submit">Найти</button></form><div id="real-search-results"></div><div id="real-map-picker" aria-label="Карта выбора участка"></div><div class="real-place-row"><strong id="real-place-name">Москва</strong><label>Участок <select id="real-map-size" aria-label="Размер реального участка">${REAL_MAP_SIZES.map(size => `<option value="${size}" ${size === 1200 ? "selected" : ""}>${size < 1000 ? `${size} × ${size} м` : `${(size / 1000).toLocaleString("ru")} × ${(size / 1000).toLocaleString("ru")} км`}</option>`).join("")}</select></label></div><p id="real-map-detail" class="muted"></p><details class="real-coordinates"><summary>Указать координаты</summary><form id="real-coordinates-form"><label>Широта<input id="real-lat" type="number" step="any" min="-80" max="80" required></label><label>Долгота<input id="real-lon" type="number" step="any" min="-179.9" max="179.9" required></label><button id="real-coordinate-button" type="submit">Показать</button></form></details><p id="real-map-message" role="status">Выберите город или нажмите на карту.</p><div class="real-map-actions"><button id="real-build" class="primary-button" disabled>Построить в игре</button><button id="real-share" class="secondary-button" disabled>${icon('link')} Скопировать ссылку</button></div><p class="real-map-note">Контуры зданий, улицы и вода — из OpenStreetMap. Высоты без данных и фасады создаются процедурно. Рельеф пока плоский. Построение заменит текущий город.<br>Поиск: <a href="https://photon.komoot.io" target="_blank" rel="noopener">Photon / OpenStreetMap</a>.</p></dialog>
  <dialog id="self-destruct-dialog" aria-labelledby="self-destruct-title"><div class="dialog-head"><div><span class="eyebrow">ГОРОД НА ОБРАТНОМ ОТСЧЁТЕ</span><h2 id="self-destruct-title">Самоуничтожение</h2></div><button class="icon-btn close-dialog" aria-label="Закрыть">${icon('x')}</button></div><p class="muted">Случайные катастрофы обрушатся на город, острова и аэропорт. В финале цепная детонация уничтожит уцелевшие объекты.</p><fieldset id="self-destruct-durations"><legend>Длительность</legend><div class="duration-options">${SELF_DESTRUCT_DURATIONS.map(duration => `<label><input type="radio" name="self-destruct-duration" value="${duration}" ${duration === 30 ? 'checked' : ''}><span>${duration}<small>сек</small></span></label>`).join('')}</div></fieldset><p class="muted self-destruct-note">Отсчёт идёт по времени симуляции: пауза и скорость влияют на него. Режим завершится, когда не останется целых объектов. Остановка отменяет новые удары; запущенные катастрофы продолжаются.</p><button id="self-destruct-start" class="primary-button">${icon('timer')} Запустить самоуничтожение ${icon('chevron')}</button><button id="self-destruct-stop-dialog" class="primary-button" hidden>${icon('x')} Остановить самоуничтожение ${icon('chevron')}</button></dialog>
  <dialog id="map-dialog"><div class="dialog-head"><div><span class="eyebrow">НОВЫЙ МИР</span><h2>Такой красивый. Пока целый.</h2></div><button class="icon-btn close-dialog" aria-label="Закрыть">${icon('x')}</button></div><p class="muted">Выберите готовый город или создайте свой. Текущие разрушения будут сброшены.</p><div class="map-presets"><button data-preset="bay" class="map-preset chosen"><div class="map-art bay"><i></i><i></i><i></i><i></i><i></i></div><strong>Нью-Хейвен</strong><small>Побережье · деловой центр</small></button><button data-preset="islands" class="map-preset"><div class="map-art islands"><i></i><i></i><i></i><i></i><i></i></div><strong>Архипелаг</strong><small>Два острова · мосты</small></button><button data-preset="night" class="map-preset"><div class="map-art night"><i></i><i></i><i></i><i></i><i></i></div><strong>Неон-Сити</strong><small>Большой город · ночь</small></button></div><div class="generator-row"><label>SEED ГОРОДА<div class="seed-input"><input id="seed" value="NEW-HAVEN" maxlength="48" aria-label="Seed города"><button id="random-seed" class="icon-btn" aria-label="Случайный seed">${icon('shuffle')}</button></div></label><label>РАЗМЕР КАРТЫ<select id="map-size"><option value="14">Компактная · 0,9 км</option><option value="18" selected>Большая · 1,1 км</option><option value="24">Огромная · 1,5 км</option></select></label></div><button id="generate" class="primary-button">${icon('city')} Создать город ${icon('chevron')}</button></dialog>
  <dialog id="place-share-dialog" aria-labelledby="place-share-title"><div class="dialog-head"><div><span class="eyebrow">ПОДЕЛИТЬСЯ УЧАСТКОМ</span><h2 id="place-share-title">Это место — по ссылке.</h2></div><button class="icon-btn close-dialog" aria-label="Закрыть">${icon('x')}</button></div><p id="place-share-description" class="muted"></p><input id="place-share-url" aria-label="Ссылка на выбранный участок" readonly spellcheck="false"><button id="place-share-copy" class="primary-button">${icon('link')} Скопировать ссылку</button><p id="place-share-status" role="status"></p><p class="muted">По ссылке автоматически построится целый город в выбранных границах. Разрушения и отряды в ссылку не входят. Для загрузки карты нужен интернет.</p></dialog>
  <dialog id="help-dialog"><div class="dialog-head"><div><span class="eyebrow">РУКОВОДСТВО ТВОРЦА</span><h2>Большой город. Большие планы.</h2></div><button class="icon-btn close-dialog" aria-label="Закрыть">${icon('x')}</button></div><div class="help-grid"><div><kbd>Клик ЛКМ</kbd><span>Применить катастрофу / высадить отряд</span></div><div><kbd>ЛКМ + движение</kbd><span>Перемещать камеру по карте</span></div><div><kbd>ПКМ + движение</kbd><span>Вращать камеру вокруг города</span></div><div><kbd>W A S D / стрелки</kbd><span>Перемещать камеру</span></div><div><kbd>Колесо / жест двумя пальцами</kbd><span>Приближать и отдалять</span></div><div><kbd>Средняя кнопка + движение</kbd><span>Передвигать обзор</span></div><div><kbd>1–9</kbd><span>Быстрый выбор катастрофы</span></div><div><kbd>Пробел</kbd><span>Пауза / продолжить</span></div><div><kbd>C / H / Esc</kbd><span>Кинорежим / камера домой / выйти</span></div></div><p class="muted">Вкладка «Десант»: выберите тип отряда и команду, нажмите на сушу. Бойцы спускаются на парашютах; разные команды ищут противника, обходят дома и стреляют. Пули останавливаются стенами. На мини-карте можно перейти к шести островным поселениям. Нажмите на самолёт, чтобы сбить его выбранной катастрофой. Потоп опускает выбранный участок: затопленная низина остаётся до восстановления города. Цунами проходит только внутри выбранного круга, направление показывает стрелка. Мощность меняет размер зоны. Доки и островные пирсы разрушаются по секциям. Все катастрофы можно сочетать. Огонь распространяется, повреждённые здания обрушиваются, обломки остаются на улицах. Ползунок мощности меняет силу и масштаб. На телефоне: короткое касание — применить инструмент; движение одним пальцем — перемещать камеру; движение двумя пальцами — вращать и наклонять; сведение и разведение пальцев — приближать и отдалять. Отпускание пальцев после жеста не применяет инструмент.</p></dialog>
  <dialog id="settings-dialog"><div class="dialog-head"><div><span class="eyebrow">ПОД ВАШ КОМПЬЮТЕР</span><h2>Графика и атмосфера</h2></div><button class="icon-btn close-dialog" aria-label="Закрыть">${icon('x')}</button></div><label class="setting-row">Качество графики<select id="quality"><option value="high">Высокое</option><option value="medium">Среднее</option><option value="low">Производительность</option></select></label><label class="setting-row">Показывать FPS<input id="fps-enabled" type="checkbox" checked></label><label class="setting-row">Солнце на небе<input id="sun-enabled" type="checkbox" checked></label><label class="setting-row">Солнечные лучи<input id="rays-enabled" type="checkbox" checked></label><label class="setting-row">Тряска камеры<input id="shake-enabled" type="checkbox" checked></label><label class="setting-row">Вспышки<input id="flash-enabled" type="checkbox" checked></label><label class="setting-row">Кровь и следы<input id="blood-enabled" type="checkbox" checked></label><p class="muted">Высокое качество: мягкие тени и свечение. Производительность: пониженное разрешение и упрощённые тени. Параметры сохраняются на этом устройстве.</p></dialog>
  `;
  const realButton = document.createElement('button'); realButton.id = 'real-maps'; realButton.className = 'real-map-entry'; realButton.innerHTML = icon('map') + '<span><strong>Реальное место</strong><small>Выберите точку на карте Земли и постройте её в игре</small></span>' + icon('chevron');
  el('map-dialog').querySelector('.map-presets')!.before(realButton);
  for (const button of document.querySelectorAll('.close-dialog')) button.addEventListener('click', () => button.closest('dialog')!.close());
  for (const dialog of document.querySelectorAll('dialog')) dialog.addEventListener('click', e => { if (e.target === dialog) { const r = dialog.getBoundingClientRect(); if ((e as MouseEvent).clientX < r.left || (e as MouseEvent).clientX > r.right || (e as MouseEvent).clientY < r.top || (e as MouseEvent).clientY > r.bottom) dialog.close(); } });
}
export function selectCard(id: DisasterId) { for (const card of document.querySelectorAll<HTMLElement>('[data-disaster]')) { const yes = card.dataset.disaster === id; card.classList.toggle('selected', yes); card.setAttribute('aria-pressed', String(yes)); } }
